---
decay_factor: 0.0005
output_stage: head
grid_sizes:
  - 13
  - 26


sub_models_configs:
- name: backbone
#  inputs: Edge element uses model's global input

  layers_config_file: config/models/yolov3_tiny/backbone.yaml
  outputs_layers: # Set outputs layers as a list or as a scalar according to topology
  - -5
  - -1

- name: neck0
  inputs:  #  a list of sub-model outputs source.
    source:
    - name: backbone
      entry_index: 1 # entry_index field is needed if source is a list instance. Otherwise - filed is redundant

  layers_config_file: config/models/yolov3_tiny/neck0.yaml
  outputs_layers:
  - -1

- name: head0
  inputs:
    source:
    - name: neck0
      entry_index: 0 #  entry_index field is needed for a list source. Otherwise - put 0 or omit entire entry_index row
  layers_config_file: config/models/yolov3_tiny/head0.yaml
  outputs_layers:
  - -1

- name: neck1
  inputs:
    source:
    - name: backbone
      entry_index: 0
    - name: neck0
      entry_index: 0
  layers_config_file: config/models/yolov3_tiny/neck1.yaml
  outputs_layers:
  - -2
  - -1


- name: head1
  inputs:
    source:
    - name: neck1
      entry_index:  0 #  entry_index field is needed for a list source. Otherwise - put 0 or omit entire entry_index row
  layers_config_file: config/models/yolov3_tiny/head1.yaml
  outputs_layers:
  - -1

