---
    layers_config:

    - type: route
      source:
        inputs:
        - 1

    - type: convolutional
      batch_normalize: 1
      filters: 128
      size: 1
      stride: 1
      pad: 1
      activation: leaky

    - type: upsample
      stride: 2

    - type: route
      source:
        layers :
        - -1
        inputs:
        - 0

    - type: convolutional
      batch_normalize: 1
      size: 3
      stride: 1
      pad: 1
      filters: 256
      activation: leaky