---
backbone:
  [
  [ -1, 1, Conv, [ 16, 3, 1, 1,1,1 ] ],  # 0-P1/2 c2, f, n, [filters,k=1, s, p,bn,activation] #0
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ]] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ 32, 3, 1 , 1,1,1] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ]] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ 64, 3, 1 , 1,1,1] ],  # 0-P1/2 c2, k=1, s=1, p #0
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ]] ],  # 0-P1/2 c2, k=1, s=1, p #5
  [ -1, 1, Conv, [ 128, 3, 1, 1,1,1 ] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ]] ],  # 0-P1/2 c2, k=1, s=1, p #5
  [ -1, 1, Conv, [ 256, 3, 1 , 1,1,1] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ]] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ 512, 3, 1 , 1,1,1] ],  # 0-P1/2 c2, k=1, s=1, p # 10
  [ -1, 1, Maxpool, [ [ 2, 2 ], [ 1,1 ]] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ 1024, 3, 1, 1,1,1 ] ],  # 0-P1/2 c2, k=1, s=1, p #12
    ]
head:
  [
  #neck0
  [ -1, 1, Conv, [ 256, 1, 1 , 1,1,1] ],  # 0-P1/2 c2, k=1, s=1, p #0 #13
#  #head0
  [ -1, 1, Conv, [ 512, 3, 1, 1,1,1 ] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ na*(nc+5), 1, 1 , 1,0,0 ] ],  # 0-P1/2 c2, k=1, s=1, p

  [ -1, 1, Decoder, [ 13 ] ],  # 1-P2/4 #15
##  #neck1
  [ 13, 1, Conv, [ 128, 1, 1, 1,1,1 ] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Upsample, [ 2 ]],  # 0-P1/2 c2, k=1, s=1, p
  [ [-1, 8], 1, Concat, [  ]],  # 0-P1/2 c2, k=1, s=1, p
###  #head1
  [ -1, 1, Conv, [ 256, 3, 1, 1,1,1 ] ],  # 0-P1/2 c2, k=1, s=1, p
  [ -1, 1, Conv, [ na*(nc+5), 1, 1 , 1,0,0] ],  # 0-P1/2 c2, k=1, s=1, p


  [ -1, 1, Decoder, [ 26 ] ],  # 1-P2/4 #15
  [ [ 15,-1 ] , 1, Output, [ nc ] ],  # 1-P2/4

  ]
