---
backbone:
  [
    [ -1, 1, Conv, [ 16, 3, 1, 1,1,1 ] ],  #  f,n,[filters,k,s,p,bn,activation] #0 #0
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ] ] ],
    [ -1, 1, Conv, [ 32, 3, 1 , 1,1,1 ] ],
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ] ] ],
    [ -1, 1, Conv, [ 64, 3, 1 , 1,1,1 ] ],
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ] ] ],  #5
    [ -1, 1, Conv, [ 128, 3, 1, 1,1,1 ] ],
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ] ] ],
    [ -1, 1, Conv, [ 256, 3, 1 , 1,1,1 ] ],
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 2,2 ] ] ],
    [ -1, 1, Conv, [ 512, 3, 1 , 1,1,1 ] ],  # 10
    [ -1, 1, Maxpool, [ [ 2, 2 ], [ 1,1 ] ] ],
    [ -1, 1, Conv, [ 1024, 3, 1, 1,1,1 ] ],  #12
  ]
head:
  [
    #neck0
    [ -1, 1, Conv, [ 256, 1, 1 , 1,1,1 ] ],  #13
    #  #head0
    [ -1, 1, Conv, [ 512, 3, 1, 1,1,1 ] ],
    [ -1, 1, Conv, [ na*(nc+5), 1, 1 , 1,0,0 ] ],
    [ -1, 1, Reshape, [ 13,13,na,(nc+5) ] ], #16
    ##  #neck1
    [ 13, 1, Conv, [ 128, 1, 1, 1,1,1 ] ],
    [ -1, 1, Upsample, [ 2 ] ],
    [ [ -1, 8 ], 1, Concat, [ ] ],
    ###  #head1
    [ -1, 1, Conv, [ 256, 3, 1, 1,1,1 ] ],
    [ -1, 1, Conv, [ na*(nc+5), 1, 1 , 1,0,0 ] ],
    [ -1, 1, Reshape, [ 26,26,na,(nc+5) ] ],
    [ [ 16,-1 ] , 1, Output, [ nc ] ],
  ]
