---
model_config_file: config/models/yolov3/model.yaml
image_size: 416
#max_detection_images: 25

#inference_input_data:
input_data_source:  image_file # [tfrecords, images_dir, image_file]
images_dir: datasets/shapes/three_mixed_shapes/blue/input/images_and_annotations_file/images
tfrecords_dir:  datasets/shapes/colors_circles_triangles_trapezoid_2sizes/input/tfrecords/test
image_file_path: datasets/coco2012/images/girl.png # datasets/shapes/three_circles/input/images_and_annotations_file/images/000001.jpg
classes_name_file: datasets/coco2012/coco.names # datasets/shapes/two_colors/class.names  #./datasets/shapes/class.names
anchors_file: datasets/coco2012/anchors.txt #datasets/shapes/anchors/shapes_yolov3_anchors.txt



#infrece_nms_params:
yolo_max_boxes: 100
nms_iou_threshold: 0.5
nms_score_threshold: 0.5

#inference_output_params:
display_result_images: True
save_result_images: True
bbox_color:
  - 1.
  - 1.
  - 1.
font_size: 15
output_dir: datasets/coco2012/output

#inference_input:
input_weights_path: checkpoints/keras_coco_yolov3.tf # /home/ronen/PycharmProjects/yolov3-tf2/checkpoints/yolov3.tf # weights/coco/girl/yolov3_train_girl.tf # weights/coco/girl/yolov3_train_coco_25.tf # checkpoints/yolov3_train_rb_circles4.tf
