---

model_config_file: config/yolov3_model.yaml
image_size: 416
#max_detection_images: 25
input_data_source:  tfrecords # [tfrecords, images_dir, image_file]
display_result_images: True
save_result_images: True
yolo_max_boxes: 100
nms_iou_threshold: 0.5
nms_score_threshold: 0.5
bbox_color:
  - 1.
  - 1.
  - 1.
font_size: 15
classes: datasets/shapes/two_colors/class.names  #./datasets/shapes/class.names
anchors_file: datasets/shapes/anchors/shapes_yolov3_anchors.txt
weights:    weights/rb_circles/yolov3_train_rb_circles4.tf
images_dir: datasets/shapes/three_mixed_shapes/blue/input/images_and_annotations_file/images
                datasets/shapes/colors_circles_triangles_trapezoid_2sizes/input/tfrecords/test
tfrecords_dir:  datasets/shapes/three_mixed_shapes/red/input/tfrecords/test
#datasets/shapes/two_colors/input/tfrecords/test
#datasets/shapes/colors_circles_triangles/input/tfrecords/test
# datasets/shapes/colors_circles_triangles_trapezoid_2sizes/input/tfrecords/test
# datasets/shapes/two_colors/input/tfrecords/test
# datasets/shapes/three_mixed_shapes/blue/input/tfrecords/test
image_file_path: datasets/shapes/three_circles/input/images_and_annotations_file/images/000001.jpg
output_dir: datasets/shapes/three_mixed_shapes/blue/output
