#! /usr/bin/env python
# coding=utf-8
# ================================================================
#   Copyright (C) 2022 . All rights reserved.
#
#   File name   : train_config.yaml
#   Author      : ronen halevy 
#   Created date:  7/19/22
#   Description :
#
# ================================================================
---
#training_dataset_config:

input_data_source: debug_data # [tfrecords, images_dir_annot_file, debug_data]
##tfrecords:
train_tfrecords: datasets/shapes/two_colors/input/tfrecords/train
val_tfrecords: datasets/shapes/two_colors/input/tfrecords/val
##plain_dataset:
images_dir: datasets/coco2012/images
annotations_path: datasets/coco2012/annotations.json

classes_name_file: datasets/coco2012/coco.names
anchors_file: datasets/coco2012/anchors.txt
dataset_cuttof_size: null # null or size limit value


dataset_repeats: 11
max_bboxes: 100


# model
model_config_file: config/models/yolov3/model.yaml
image_size: 416
grid_sizes_table:
  - 13
  - 26
  - 52

training_mode: fit # 'model execution mode. choices=[eager_tf, fit]'

batch_size: 8
epochs: 1000
learning_rate: 0.001
early_stopping: False # enables early_stopping callback
early_stop_patience: 13 # an early_stopping callback parameter
weights_save_peroid: 4
output_checkpoints_path: 'checkpoints/yolov3_train.tf' # prefix of path checkpoints save


transfer_learning_config:
  transfer_list: # all, none, backbone, or neck (equivalent to listing backbone and neck)
#    - all
#    - none
#    - all
    - backbone
#    - neck
#    - head
  freeze_train_list: # Can omit. Note: selecting neck does not imply to  backbone
     - none
#    - backbone
#    - neck
  batch_norm_freeze_list:  # Can omit. Note: selecting neck does not imply to  backbone
    - none
#    - backbone
#    - neck
#    - head

  input_weights_path: checkpoints/my_keras_coco_yolov3.tf

#training_etc_config:
debug_mode: False # Debug step-by-step trace graph mode functions
render_dataset_example: False



