#! /usr/bin/env python
# coding=utf-8
# ================================================================
#   Copyright (C) 2022 . All rights reserved.
#
#   File name   : train_config.yaml
#   Author      : ronen halevy 
#   Created date:  7/19/22
#   Description :
#
# ================================================================
---

# dataset:
input_data_source: tfrecords # images_dir_annot_file # [tfrecords, images_dir_annot_file, coco_debug_data]
#tfrecords:
train_tfrecords:  datasets/shapes/red_circle/input/tfrecords/train # datasets/shapes/circle_and_triangle/input/tfrecords/train
val_tfrecords: datasets/shapes/red_circle/input/tfrecords/val # datasets/shapes/circle_and_triangle/input/tfrecords/val
#plain_dataset:
images_dir: datasets/shapes/three_circles/input/images_and_annotations_file/images #datasets/shapes/three_mixed_shapes/red/input/images_and_annotations/images # directory location of input images used in non-tfrecords mode
annotations_path: ddatasets/shapes/three_circles/input/images_and_annotations_file/annotations.yaml
classes_name_file: datasets/shapes/circle_and_triangle/class.names # 'datasets/shapes/class.names'
anchors_file: datasets/shapes/anchors/shapes_yolov3_anchors.txt
dataset_cuttof_size: null # null or size limit value

dataset_repeats: 0
max_bboxes: 100

#model
model_config_file: config/models/yolov3/model.yaml # config/yolov3_model.yaml
image_size: 416

#algorithm
mode: fit # eager_tf # fit # 'model execution mode. choices=[eager_tf, fit]'
batch_size: 8
epochs: 1000
learning_rate: 0.001
early_stopping: False # enables early_stopping callback
early_stop_patience: 13 # an early_stopping callback parameter

#weights transfer

load_weights: False # backbone, backbone_and_neck, all, none
training_mode:
  - backbone: enable #enable, freeze, fine_tune
  - neck: enable  #enable, freeze, fine_tune
  - head: enable  #enable, freeze, fine_tune
load_checkpoints_path: checkpoints/yolov3_train1.tf # checkpoints/yolov3_train_rb_circles.tf #'checkpoints/yolov3_train_newclass5.tf' #path to pretrained weights file


# operation modes
debug_mode: False #  run developpers' test code lines


#output setup
render_dataset_example: False
weights_save_peroid: 4
output_checkpoints_path: checkpoints/yolov3_train.tf # prefix of path checkpoints save

