---
    layers_config:

    - type: route
      source:
        inputs:
          entries: anyvalue # if inputs source holds a scalar and not a list, then entires value is 'don't care'



    - type: convolutional
      size: 1
      stride: 1
      pad: 1
      filters:  3*(2+2+1+nclasses) # ngrids*(xy_field+wh_field+obj_field+nclasses)
      activation: linear
    - type: yolo
      jitter: .3

