---
    layers_config:

    - type: route
      source:
        inputs:
        - 0 # btw - if inputs source holds a scalar and not a list, then inputs value is actually 'don't care'
    - type: convolutional
      batch_normalize: 1
      size: 3
      stride: 1
      pad: 1
      filters: 1024
      activation: leaky

    - type: convolutional
      size: 1
      stride: 1
      pad: 1
      filters:  3*(2+2+1+nclasses) # ngrids*(xy_field+wh_field+obj_field+nclasses)
      activation: linear
    - type: yolo
      grid_size: 13
      jitter: .3

