---
    layers_config:

    - type: route
      source:
        inputs: anyvalue # field value is don't care if inputs is a scalar

    - type: convolutional
      batch_normalize: 1
      filters: 512
      size: 1
      stride: 1
      pad: 1
      activation: leaky

    - type: convolutional
      batch_normalize: 1
      size: 3
      stride: 1
      pad: 1
      filters: 1024
      activation: leaky

    - type: convolutional
      batch_normalize: 1
      filters: 512
      size: 1
      stride: 1
      pad: 1
      activation: leaky

    - type: convolutional
      batch_normalize: 1
      size: 3
      stride: 1
      pad: 1
      filters: 1024
      activation: leaky

    - type: convolutional
      batch_normalize: 1
      filters: 512
      size: 1
      stride: 1
      pad: 1
      activation: leaky

    -type: output
    list:
      layers:
      - 1
