# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license

# Parameters
#nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors:
  - [ 10,13, 16,30, 33,23 ]  # P3/8
  - [ 30,61, 62,45, 59,119 ]  # P4/16
  - [ 116,90, 156,198, 373,326 ]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  [
    [ -1, 1, Conv, [ 32, 3, 1 ] ],  # 0-P1/2 c2, k=1, s=1, p #0
    [ -1, 1, Conv, [ 64, 3, 2 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 32, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 64, 3, 1 ] ],  # 1-P2/4
    [ [ 1,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 3, 2 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 64, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 3, 1 ] ],  # 1-P2/4
    [ [ 5,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 64, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 3, 1 ] ],  # 1-P2/4 #10
    [ [ 8,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 2 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 12,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 15,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4 #20
    [ [ 18,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 21,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 24,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 27,-1 ], 1, ADD, [ ] ],  # 1-P2/4 #30
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 30,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ [ 33,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 2 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 37,-1 ], 1, ADD, [ ] ],  # 1-P2/4 #40
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 40,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 43,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 46,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4 #50
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 49,-1 ], 1, ADD, [ ] ],  # 1-P2/
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 52,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ [ 55,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4 #60
    [ [ 58,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 2 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4
    [ [ 62,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/
    [ [ 65,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4 #70
    [ [ 68,-1 ], 1, ADD, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4
    [ [ 71,-1 ], 1, ADD, [ ] ],  # 1-P2/4 #74
  ]
head:
  [ ###neck0
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 1-P2/4 #79
#    #head0
    [ -1, 1, Conv, [ 1024, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, decoder, [ 13 ] ],  # 1-P2/4 #81
    ##neck1L
    [ 79, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4 #82
    [ -1, 1, upsample, [ 2 ] ],  # 1-P2/4
    [ [ 61,-1 ], 1, Concat, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4 #85
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 1-P2/4 #89
#    #head 1
    [ -1, 1, Conv, [ 512, 3, 1 ] ],  # 1-P2/4 #90
    [ -1, 1, decoder, [ 26 ] ],  # 1-P2/4 #91
#    # neck2
    [ 89, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, upsample, [ 2 ] ],  # 1-P2/4
    [ [ 36,-1 ], 1, Concat, [ ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, Conv, [ 128, 1, 1 ] ],  # 1-P2/4
#    ### head2
    [ -1, 1, Conv, [ 256, 3, 1 ] ],  # 1-P2/4
    [ -1, 1, decoder, [52 ]],  # 1-P2/4
    [ [81,91,-1] , 1, detect, [nc] ],  # 1-P2/4


  ]