# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license

# Parameters
#nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors:
  - [ 10,13, 16,30, 33,23 ]  # P3/8
  - [ 30,61, 62,45, 59,119 ]  # P4/16
  - [ 116,90, 156,198, 373,326 ]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  [
    [ -1, 1, Conv, [ 32, 3, 1,1,1,1 ] ],  #  f,n,[filters,k,s,p,bn,activation] #0 #0
    [ -1, 1, Conv, [ 64, 3, 2,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 32, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 64, 3, 1,1,1,1 ] ],  # 
    [ [ 1,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 3, 2,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 64, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 128, 3, 1,1,1,1 ] ],  # 
    [ [ 5,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 64, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 128, 3, 1,1,1,1 ] ],  #  #10
    [ [ 8,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 3, 2,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 12,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 15,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  #  #20
    [ [ 18,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 21,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 24,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 27,-1 ], 1, Shortcut, [ ] ],  #  #30
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 30,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  # 
    [ [ 33,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 512, 3, 2,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 37,-1 ], 1, Shortcut, [ ] ],  #  #40
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 40,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 43,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 46,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  #  #50
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 49,-1 ], 1, Shortcut, [ ] ],  # 1-P2/
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 52,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  # 
    [ [ 55,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  #  #60
    [ [ 58,-1 ], 1, Shortcut, [ ] ],  #  #61
    [ -1, 1, Conv, [ 1024, 3, 2,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  # 
    [ [ 62,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  # 1-P2/
    [ [ 65,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  #  #70
    [ [ 68,-1 ], 1, Shortcut, [ ] ],  #
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  # 
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  # 
    [ [ 71,-1 ], 1, Shortcut, [ ] ],  #  #74
  ]
head:
  [ ###neck0
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 512, 1, 1,1,1,1 ] ],  #  #79
###    #head0
    [ -1, 1, Conv, [ 1024, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ na*(nc+5), 1, 1,1, 0,0 ] ],  #
    [ -1, 1, Reshape, [ 13,13,na,(nc+5) ] ],  # 82

#    #    ##neck1L
    [ 79, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  #  #83
    [ -1, 1, Upsample, [ 2 ] ],  #
    [ [ 61,-1 ], 1, Concat, [ ] ],  #85
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 256, 1, 1,1,1,1 ] ],  #  90
##    #head 1
    [ -1, 1, Conv, [ 512, 3, 1,1,1,1 ] ],  #  #91
    [ -1, 1, Conv, [ na*(nc+5), 1, 1,1,0,0 ] ],  #

    [ -1, 1, Reshape, [ 26,26,na,(nc+5) ] ],  #93
#
#    ##    # neck2
    [ 90, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Upsample, [ 2 ] ],  #
    [ [ 36,-1 ], 1, Concat, [ ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ 128, 1, 1,1,1,1 ] ],  #
##    ### head2
    [ -1, 1, Conv, [ 256, 3, 1,1,1,1 ] ],  #
    [ -1, 1, Conv, [ na*(nc+5), 1, 1,1,0,0 ] ],  #
    [ -1, 1, Reshape, [52,52,na,(nc+5) ]],  #
    [ [82,93,-1] , 1, Output, [nc] ],  #
  ]